name: ecsite-sample
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: deploy
    ports:
      - "8050:8050"
    environment:
      PORT: 8050
      DB_HOST: db
      DB_PORT: 5432
    tty: true
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
